// This file is auto-generated by supabase/generate-zod-schema.ts. Do not edit manually.

import { z } from 'zod';

export const jsonSchema = z.any();

export const appRoleSchema = z.union([z.literal('admin'), z.literal('staff'), z.literal('community_admin')]);
export const communityJoinModeSchema = z.union([z.literal('INVITATION_ONLY'), z.literal('OPEN_TO_ALL')]);
export const communityMemberStatusSchema = z.union([z.literal('INVITED'), z.literal('REQUESTED'), z.literal('ACCEPTED'), z.literal('REQUEST_REJECTED'), z.literal('REMOVED'), z.literal('INVITATION_REJECTED')]);
export const eventTypeSchema = z.union([z.literal('ONLINE'), z.literal('OFFLINE'), z.literal('ONDEMAND')]);
export const recommendationStatusSchema = z.union([z.literal('ACCEPTED'), z.literal('REJECTED'), z.literal('NOT_USED')]);
export const cCommunityRowSchema = z.object({
  created_at: z.string(),
  detail: z.string().nullable(),
  id: z.number(),
  image_url: z.string(),
  join_mode: communityJoinModeSchema,
  manager_id: z.string().nullable(),
  name: z.string(),
});

export const cCommunityInsertSchema = z.object({
  created_at: z.string().optional(),
  detail: z.string().optional().nullable(),
  id: z.number().optional(),
  image_url: z.string(),
  join_mode: communityJoinModeSchema.optional(),
  manager_id: z.string().optional().nullable(),
  name: z.string(),
});

export const cCommunityUpdateSchema = z.object({
  created_at: z.string().optional(),
  detail: z.string().optional().nullable(),
  id: z.number().optional(),
  image_url: z.string().optional(),
  join_mode: communityJoinModeSchema.optional(),
  manager_id: z.string().optional().nullable(),
  name: z.string().optional(),
});

export const cCommunityMembersRowSchema = z.object({
  community_id: z.number(),
  created_at: z.string(),
  status: communityMemberStatusSchema.nullable(),
  user_id: z.string(),
});

export const cCommunityMembersInsertSchema = z.object({
  community_id: z.number(),
  created_at: z.string().optional(),
  status: communityMemberStatusSchema.optional().nullable(),
  user_id: z.string(),
});

export const cCommunityMembersUpdateSchema = z.object({
  community_id: z.number().optional(),
  created_at: z.string().optional(),
  status: communityMemberStatusSchema.optional().nullable(),
  user_id: z.string().optional(),
});

export const cCommunityPostsRowSchema = z.object({
  community_id: z.number(),
  created_at: z.string(),
  created_by: z.string().nullable(),
  detail_html: z.string().nullable(),
  detail_text: z.string().nullable(),
  id: z.number(),
  image_url: z.string().nullable(),
  title: z.string(),
});

export const cCommunityPostsInsertSchema = z.object({
  community_id: z.number(),
  created_at: z.string().optional(),
  created_by: z.string().optional().nullable(),
  detail_html: z.string().optional().nullable(),
  detail_text: z.string().optional().nullable(),
  id: z.number().optional(),
  image_url: z.string().optional().nullable(),
  title: z.string(),
});

export const cCommunityPostsUpdateSchema = z.object({
  community_id: z.number().optional(),
  created_at: z.string().optional(),
  created_by: z.string().optional().nullable(),
  detail_html: z.string().optional().nullable(),
  detail_text: z.string().optional().nullable(),
  id: z.number().optional(),
  image_url: z.string().optional().nullable(),
  title: z.string().optional(),
});

export const conciergeRowSchema = z.object({
  category_id: z.number(),
  created_at: z.string(),
  extra_data: jsonSchema,
  id: z.number(),
  name: z.string(),
  status: z.string(),
  user_id: z.string(),
});

export const conciergeInsertSchema = z.object({
  category_id: z.number(),
  created_at: z.string().optional(),
  extra_data: jsonSchema,
  id: z.number().optional(),
  name: z.string(),
  status: z.string(),
  user_id: z.string(),
});

export const conciergeUpdateSchema = z.object({
  category_id: z.number().optional(),
  created_at: z.string().optional(),
  extra_data: jsonSchema.optional(),
  id: z.number().optional(),
  name: z.string().optional(),
  status: z.string().optional(),
  user_id: z.string().optional(),
});

export const conciergeCategoryRowSchema = z.object({
  created_at: z.string(),
  detail: jsonSchema,
  icon: z.string(),
  id: z.number(),
  title: z.string(),
});

export const conciergeCategoryInsertSchema = z.object({
  created_at: z.string().optional(),
  detail: jsonSchema,
  icon: z.string(),
  id: z.number().optional(),
  title: z.string(),
});

export const conciergeCategoryUpdateSchema = z.object({
  created_at: z.string().optional(),
  detail: jsonSchema.optional(),
  icon: z.string().optional(),
  id: z.number().optional(),
  title: z.string().optional(),
});

export const conciergeMessageRowSchema = z.object({
  concierge_id: z.number(),
  created_at: z.string(),
  id: z.number(),
  image_path: z.string().nullable(),
  message: z.string().nullable(),
  sender_id: z.string().nullable(),
  user_id: z.string().nullable(),
});

export const conciergeMessageInsertSchema = z.object({
  concierge_id: z.number(),
  created_at: z.string().optional(),
  id: z.number().optional(),
  image_path: z.string().optional().nullable(),
  message: z.string().optional().nullable(),
  sender_id: z.string().optional().nullable(),
  user_id: z.string().optional().nullable(),
});

export const conciergeMessageUpdateSchema = z.object({
  concierge_id: z.number().optional(),
  created_at: z.string().optional(),
  id: z.number().optional(),
  image_path: z.string().optional().nullable(),
  message: z.string().optional().nullable(),
  sender_id: z.string().optional().nullable(),
  user_id: z.string().optional().nullable(),
});

export const depUUserRolesRowSchema = z.object({
  id: z.number(),
  role: appRoleSchema,
  user_id: z.string(),
});

export const depUUserRolesInsertSchema = z.object({
  id: z.number().optional(),
  role: appRoleSchema,
  user_id: z.string(),
});

export const depUUserRolesUpdateSchema = z.object({
  id: z.number().optional(),
  role: appRoleSchema.optional(),
  user_id: z.string().optional(),
});

export const mAppSettingsRowSchema = z.object({
  created_at: z.string(),
  id: z.number(),
  name: z.string(),
  value: jsonSchema,
});

export const mAppSettingsInsertSchema = z.object({
  created_at: z.string().optional(),
  id: z.number().optional(),
  name: z.string(),
  value: jsonSchema,
});

export const mAppSettingsUpdateSchema = z.object({
  created_at: z.string().optional(),
  id: z.number().optional(),
  name: z.string().optional(),
  value: jsonSchema.optional(),
});

export const mAutoSupportMessagesRowSchema = z.object({
  content: z.string(),
  created_at: z.string(),
  id: z.string(),
  image_url: z.string().nullable(),
  send_time: z.string(),
  user_id: z.string(),
});

export const mAutoSupportMessagesInsertSchema = z.object({
  content: z.string(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  image_url: z.string().optional().nullable(),
  send_time: z.string().optional(),
  user_id: z.string(),
});

export const mAutoSupportMessagesUpdateSchema = z.object({
  content: z.string().optional(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  image_url: z.string().optional().nullable(),
  send_time: z.string().optional(),
  user_id: z.string().optional(),
});

export const mIndustriesRowSchema = z.object({
  id: z.number(),
  name: z.string(),
});

export const mIndustriesInsertSchema = z.object({
  id: z.number().optional(),
  name: z.string(),
});

export const mIndustriesUpdateSchema = z.object({
  id: z.number().optional(),
  name: z.string().optional(),
});

export const mInterestsRowSchema = z.object({
  id: z.number(),
  name: z.string(),
});

export const mInterestsInsertSchema = z.object({
  id: z.number().optional(),
  name: z.string(),
});

export const mInterestsUpdateSchema = z.object({
  id: z.number().optional(),
  name: z.string().optional(),
});

export const mSkillsRowSchema = z.object({
  id: z.number(),
  name: z.string(),
});

export const mSkillsInsertSchema = z.object({
  id: z.number().optional(),
  name: z.string(),
});

export const mSkillsUpdateSchema = z.object({
  id: z.number().optional(),
  name: z.string().optional(),
});

export const randomUsersRowSchema = z.object({
  avatar_url: z.string().nullable(),
  birthday: z.string().nullable(),
  created_at: z.string().nullable(),
  email: z.string().nullable(),
  expo_push_notification_token: z.string().nullable(),
  firstname: z.string().nullable(),
  firstname_kana: z.string().nullable(),
  hide_age: z.boolean().nullable(),
  id: z.string().nullable(),
  introduction: z.string().nullable(),
  last_recommended_date: z.string().nullable(),
  lastname: z.string().nullable(),
  lastname_kana: z.string().nullable(),
  profile_bg_url: z.string().nullable(),
  sns_link1: z.string().nullable(),
  sns_link2: z.string().nullable(),
  sns_link3: z.string().nullable(),
});

export const randomUsersInsertSchema = z.object({
  avatar_url: z.string().optional().nullable(),
  birthday: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  email: z.string().optional().nullable(),
  expo_push_notification_token: z.string().optional().nullable(),
  firstname: z.string().optional().nullable(),
  firstname_kana: z.string().optional().nullable(),
  hide_age: z.boolean().optional().nullable(),
  id: z.string().optional().nullable(),
  introduction: z.string().optional().nullable(),
  last_recommended_date: z.string().optional().nullable(),
  lastname: z.string().optional().nullable(),
  lastname_kana: z.string().optional().nullable(),
  profile_bg_url: z.string().optional().nullable(),
  sns_link1: z.string().optional().nullable(),
  sns_link2: z.string().optional().nullable(),
  sns_link3: z.string().optional().nullable(),
});

export const randomUsersUpdateSchema = z.object({
  avatar_url: z.string().optional().nullable(),
  birthday: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  email: z.string().optional().nullable(),
  expo_push_notification_token: z.string().optional().nullable(),
  firstname: z.string().optional().nullable(),
  firstname_kana: z.string().optional().nullable(),
  hide_age: z.boolean().optional().nullable(),
  id: z.string().optional().nullable(),
  introduction: z.string().optional().nullable(),
  last_recommended_date: z.string().optional().nullable(),
  lastname: z.string().optional().nullable(),
  lastname_kana: z.string().optional().nullable(),
  profile_bg_url: z.string().optional().nullable(),
  sns_link1: z.string().optional().nullable(),
  sns_link2: z.string().optional().nullable(),
  sns_link3: z.string().optional().nullable(),
});

export const revenueCatProcessedEventsRowSchema = z.object({
  created_at: z.string(),
  id: z.number(),
});

export const revenueCatProcessedEventsInsertSchema = z.object({
  created_at: z.string(),
  id: z.number().optional(),
});

export const revenueCatProcessedEventsUpdateSchema = z.object({
  created_at: z.string().optional(),
  id: z.number().optional(),
});

export const sMatchesRowSchema = z.object({
  created_at: z.string(),
  id: z.number(),
  staff_id: z.string(),
  staff_last_seen_at: z.string().nullable(),
  user_id: z.string(),
  user_last_seen_at: z.string().nullable(),
});

export const sMatchesInsertSchema = z.object({
  created_at: z.string().optional(),
  id: z.number().optional(),
  staff_id: z.string(),
  staff_last_seen_at: z.string().optional().nullable(),
  user_id: z.string(),
  user_last_seen_at: z.string().optional().nullable(),
});

export const sMatchesUpdateSchema = z.object({
  created_at: z.string().optional(),
  id: z.number().optional(),
  staff_id: z.string().optional(),
  staff_last_seen_at: z.string().optional().nullable(),
  user_id: z.string().optional(),
  user_last_seen_at: z.string().optional().nullable(),
});

export const sMessagesRowSchema = z.object({
  content: z.string(),
  created_at: z.string(),
  id: z.number(),
  image_url: z.string().nullable(),
  match_id: z.number(),
  sender_id: z.string(),
});

export const sMessagesInsertSchema = z.object({
  content: z.string(),
  created_at: z.string().optional(),
  id: z.number().optional(),
  image_url: z.string().optional().nullable(),
  match_id: z.number(),
  sender_id: z.string(),
});

export const sMessagesUpdateSchema = z.object({
  content: z.string().optional(),
  created_at: z.string().optional(),
  id: z.number().optional(),
  image_url: z.string().optional().nullable(),
  match_id: z.number().optional(),
  sender_id: z.string().optional(),
});

export const sStaffCategoriesRowSchema = z.object({
  id: z.number(),
  image: z.string(),
  name: z.string(),
});

export const sStaffCategoriesInsertSchema = z.object({
  id: z.number().optional(),
  image: z.string(),
  name: z.string(),
});

export const sStaffCategoriesUpdateSchema = z.object({
  id: z.number().optional(),
  image: z.string().optional(),
  name: z.string().optional(),
});

export const sStaffCategoriesRelRowSchema = z.object({
  staff_category_id: z.number(),
  user_id: z.string(),
});

export const sStaffCategoriesRelInsertSchema = z.object({
  staff_category_id: z.number(),
  user_id: z.string(),
});

export const sStaffCategoriesRelUpdateSchema = z.object({
  staff_category_id: z.number().optional(),
  user_id: z.string().optional(),
});

export const sStaffImagesRowSchema = z.object({
  id: z.number(),
  image_path: z.string().nullable(),
  user_id: z.string(),
});

export const sStaffImagesInsertSchema = z.object({
  id: z.number().optional(),
  image_path: z.string().optional().nullable(),
  user_id: z.string(),
});

export const sStaffImagesUpdateSchema = z.object({
  id: z.number().optional(),
  image_path: z.string().optional().nullable(),
  user_id: z.string().optional(),
});

export const sStaffWithCategoryRowSchema = z.object({
  avatar_url: z.string().nullable(),
  category_id: z.number().nullable(),
  category_image: z.string().nullable(),
  category_name: z.string().nullable(),
  created_at: z.string().nullable(),
  firstname: z.string().nullable(),
  firstname_kana: z.string().nullable(),
  id: z.string().nullable(),
  introduction: z.string().nullable(),
  lastname: z.string().nullable(),
  lastname_kana: z.string().nullable(),
  location: z.string().nullable(),
});

export const sStaffWithCategoryInsertSchema = z.object({
  avatar_url: z.string().optional().nullable(),
  category_id: z.number().optional().nullable(),
  category_image: z.string().optional().nullable(),
  category_name: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  firstname: z.string().optional().nullable(),
  firstname_kana: z.string().optional().nullable(),
  id: z.string().optional().nullable(),
  introduction: z.string().optional().nullable(),
  lastname: z.string().optional().nullable(),
  lastname_kana: z.string().optional().nullable(),
  location: z.string().optional().nullable(),
});

export const sStaffWithCategoryUpdateSchema = z.object({
  avatar_url: z.string().optional().nullable(),
  category_id: z.number().optional().nullable(),
  category_image: z.string().optional().nullable(),
  category_name: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  firstname: z.string().optional().nullable(),
  firstname_kana: z.string().optional().nullable(),
  id: z.string().optional().nullable(),
  introduction: z.string().optional().nullable(),
  lastname: z.string().optional().nullable(),
  lastname_kana: z.string().optional().nullable(),
  location: z.string().optional().nullable(),
});

export const uEventAttendsRowSchema = z.object({
  event_id: z.number(),
  user_id: z.string(),
});

export const uEventAttendsInsertSchema = z.object({
  event_id: z.number(),
  user_id: z.string(),
});

export const uEventAttendsUpdateSchema = z.object({
  event_id: z.number().optional(),
  user_id: z.string().optional(),
});

export const uEventCategoriesRowSchema = z.object({
  created_at: z.string(),
  display_order: z.number().nullable(),
  id: z.number(),
  image_url: z.string(),
  title: z.string(),
});

export const uEventCategoriesInsertSchema = z.object({
  created_at: z.string().optional(),
  display_order: z.number().optional().nullable(),
  id: z.number().optional(),
  image_url: z.string(),
  title: z.string(),
});

export const uEventCategoriesUpdateSchema = z.object({
  created_at: z.string().optional(),
  display_order: z.number().optional().nullable(),
  id: z.number().optional(),
  image_url: z.string().optional(),
  title: z.string().optional(),
});

export const uEventReviewsRowSchema = z.object({
  comment: z.string().nullable(),
  created_at: z.string(),
  event_id: z.number(),
  id: z.number(),
  star: z.number(),
  title: z.string(),
  user_id: z.string(),
});

export const uEventReviewsInsertSchema = z.object({
  comment: z.string().optional().nullable(),
  created_at: z.string().optional(),
  event_id: z.number(),
  id: z.number().optional(),
  star: z.number(),
  title: z.string(),
  user_id: z.string(),
});

export const uEventReviewsUpdateSchema = z.object({
  comment: z.string().optional().nullable(),
  created_at: z.string().optional(),
  event_id: z.number().optional(),
  id: z.number().optional(),
  star: z.number().optional(),
  title: z.string().optional(),
  user_id: z.string().optional(),
});

export const uEventTicketsRowSchema = z.object({
  capacity: z.number().nullable(),
  event_id: z.number(),
  id: z.number(),
  name: z.string(),
  price: z.number().nullable(),
});

export const uEventTicketsInsertSchema = z.object({
  capacity: z.number().optional().nullable(),
  event_id: z.number(),
  id: z.number().optional(),
  name: z.string(),
  price: z.number().optional().nullable(),
});

export const uEventTicketsUpdateSchema = z.object({
  capacity: z.number().optional().nullable(),
  event_id: z.number().optional(),
  id: z.number().optional(),
  name: z.string().optional(),
  price: z.number().optional().nullable(),
});

export const uEventsRowSchema = z.object({
  address_address1: z.string().nullable(),
  address_address2: z.string().nullable(),
  address_country: z.string().nullable(),
  address_prefecture: z.string().nullable(),
  body_html: z.string().nullable(),
  category: z.number(),
  community_id: z.number().nullable(),
  created_at: z.string(),
  created_by: z.string().nullable(),
  detail: z.string(),
  end_datetime: z.string().nullable(),
  entry_end_datetime: z.string().nullable(),
  entry_start_datetime: z.string().nullable(),
  featured: z.number().nullable(),
  has_after_party: z.boolean().nullable(),
  id: z.number(),
  image_url: z.string(),
  is_free: z.boolean().nullable(),
  is_published: z.boolean().nullable(),
  latitude: z.number().nullable(),
  longitude: z.number().nullable(),
  name: z.string(),
  office_name: z.string().nullable(),
  place: z.string().nullable(),
  place_url: z.string().nullable(),
  price: z.number().nullable(),
  short_detail: z.string().nullable(),
  start_datetime: z.string().nullable(),
  sub_category_id: z.number().nullable(),
  total_capacity: z.number().nullable(),
  type: eventTypeSchema,
  use_map: z.boolean().nullable(),
});

export const uEventsInsertSchema = z.object({
  address_address1: z.string().optional().nullable(),
  address_address2: z.string().optional().nullable(),
  address_country: z.string().optional().nullable(),
  address_prefecture: z.string().optional().nullable(),
  body_html: z.string().optional().nullable(),
  category: z.number(),
  community_id: z.number().optional().nullable(),
  created_at: z.string().optional(),
  created_by: z.string().optional().nullable(),
  detail: z.string(),
  end_datetime: z.string().optional().nullable(),
  entry_end_datetime: z.string().optional().nullable(),
  entry_start_datetime: z.string().optional().nullable(),
  featured: z.number().optional().nullable(),
  has_after_party: z.boolean().optional().nullable(),
  id: z.number().optional(),
  image_url: z.string(),
  is_free: z.boolean().optional().nullable(),
  is_published: z.boolean().optional().nullable(),
  latitude: z.number().optional().nullable(),
  longitude: z.number().optional().nullable(),
  name: z.string(),
  office_name: z.string().optional().nullable(),
  place: z.string().optional().nullable(),
  place_url: z.string().optional().nullable(),
  price: z.number().optional().nullable(),
  short_detail: z.string().optional().nullable(),
  start_datetime: z.string().optional().nullable(),
  sub_category_id: z.number().optional().nullable(),
  total_capacity: z.number().optional().nullable(),
  type: eventTypeSchema,
  use_map: z.boolean().optional().nullable(),
});

export const uEventsUpdateSchema = z.object({
  address_address1: z.string().optional().nullable(),
  address_address2: z.string().optional().nullable(),
  address_country: z.string().optional().nullable(),
  address_prefecture: z.string().optional().nullable(),
  body_html: z.string().optional().nullable(),
  category: z.number().optional(),
  community_id: z.number().optional().nullable(),
  created_at: z.string().optional(),
  created_by: z.string().optional().nullable(),
  detail: z.string().optional(),
  end_datetime: z.string().optional().nullable(),
  entry_end_datetime: z.string().optional().nullable(),
  entry_start_datetime: z.string().optional().nullable(),
  featured: z.number().optional().nullable(),
  has_after_party: z.boolean().optional().nullable(),
  id: z.number().optional(),
  image_url: z.string().optional(),
  is_free: z.boolean().optional().nullable(),
  is_published: z.boolean().optional().nullable(),
  latitude: z.number().optional().nullable(),
  longitude: z.number().optional().nullable(),
  name: z.string().optional(),
  office_name: z.string().optional().nullable(),
  place: z.string().optional().nullable(),
  place_url: z.string().optional().nullable(),
  price: z.number().optional().nullable(),
  short_detail: z.string().optional().nullable(),
  start_datetime: z.string().optional().nullable(),
  sub_category_id: z.number().optional().nullable(),
  total_capacity: z.number().optional().nullable(),
  type: eventTypeSchema.optional(),
  use_map: z.boolean().optional().nullable(),
});

export const uJobIndustriesRowSchema = z.object({
  industry: z.number(),
  job: z.number(),
  user_id: z.string(),
});

export const uJobIndustriesInsertSchema = z.object({
  industry: z.number(),
  job: z.number(),
  user_id: z.string(),
});

export const uJobIndustriesUpdateSchema = z.object({
  industry: z.number().optional(),
  job: z.number().optional(),
  user_id: z.string().optional(),
});

export const uJobsRowSchema = z.object({
  company_established_year: z.number().nullable(),
  company_name: z.string().nullable(),
  created_at: z.string().nullable(),
  homepage: z.string().nullable(),
  id: z.number(),
  join_date: z.string(),
  left_date: z.string().nullable(),
  position: z.string().nullable(),
  salary_range: z.string().nullable(),
  user_id: z.string(),
});

export const uJobsInsertSchema = z.object({
  company_established_year: z.number().optional().nullable(),
  company_name: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  homepage: z.string().optional().nullable(),
  id: z.number().optional(),
  join_date: z.string(),
  left_date: z.string().optional().nullable(),
  position: z.string().optional().nullable(),
  salary_range: z.string().optional().nullable(),
  user_id: z.string(),
});

export const uJobsUpdateSchema = z.object({
  company_established_year: z.number().optional().nullable(),
  company_name: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  homepage: z.string().optional().nullable(),
  id: z.number().optional(),
  join_date: z.string().optional(),
  left_date: z.string().optional().nullable(),
  position: z.string().optional().nullable(),
  salary_range: z.string().optional().nullable(),
  user_id: z.string().optional(),
});

export const uMatchReportsRowSchema = z.object({
  created_at: z.string(),
  detail: z.string(),
  id: z.number(),
  match_id: z.number(),
  reporter_id: z.string(),
});

export const uMatchReportsInsertSchema = z.object({
  created_at: z.string().optional(),
  detail: z.string(),
  id: z.number().optional(),
  match_id: z.number(),
  reporter_id: z.string(),
});

export const uMatchReportsUpdateSchema = z.object({
  created_at: z.string().optional(),
  detail: z.string().optional(),
  id: z.number().optional(),
  match_id: z.number().optional(),
  reporter_id: z.string().optional(),
});

export const uMatchesRowSchema = z.object({
  created_at: z.string().nullable(),
  id: z.number(),
  user_1_blocked: z.boolean().nullable(),
  user_2_blocked: z.boolean().nullable(),
  user1_id: z.string(),
  user1_last_seen_at: z.string().nullable(),
  user2_id: z.string(),
  user2_last_seen_at: z.string().nullable(),
});

export const uMatchesInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.number().optional(),
  user_1_blocked: z.boolean().optional().nullable(),
  user_2_blocked: z.boolean().optional().nullable(),
  user1_id: z.string(),
  user1_last_seen_at: z.string().optional().nullable(),
  user2_id: z.string(),
  user2_last_seen_at: z.string().optional().nullable(),
});

export const uMatchesUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.number().optional(),
  user_1_blocked: z.boolean().optional().nullable(),
  user_2_blocked: z.boolean().optional().nullable(),
  user1_id: z.string().optional(),
  user1_last_seen_at: z.string().optional().nullable(),
  user2_id: z.string().optional(),
  user2_last_seen_at: z.string().optional().nullable(),
});

export const uMessagesRowSchema = z.object({
  content: z.string(),
  created_at: z.string().nullable(),
  id: z.string(),
  image_url: z.string().nullable(),
  match_id: z.number(),
  user_id: z.string(),
});

export const uMessagesInsertSchema = z.object({
  content: z.string(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  image_url: z.string().optional().nullable(),
  match_id: z.number(),
  user_id: z.string(),
});

export const uMessagesUpdateSchema = z.object({
  content: z.string().optional(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  image_url: z.string().optional().nullable(),
  match_id: z.number().optional(),
  user_id: z.string().optional(),
});

export const uRecommendationsRowSchema = z.object({
  created_at: z.string().nullable(),
  id: z.number(),
  last_action_at: z.string().nullable(),
  status: recommendationStatusSchema.nullable(),
  user1_id: z.string(),
  user2_id: z.string(),
});

export const uRecommendationsInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.number().optional(),
  last_action_at: z.string().optional().nullable(),
  status: recommendationStatusSchema.optional().nullable(),
  user1_id: z.string(),
  user2_id: z.string(),
});

export const uRecommendationsUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.number().optional(),
  last_action_at: z.string().optional().nullable(),
  status: recommendationStatusSchema.optional().nullable(),
  user1_id: z.string().optional(),
  user2_id: z.string().optional(),
});

export const uUserIndustriesRowSchema = z.object({
  industry_id: z.number(),
  user_id: z.string(),
});

export const uUserIndustriesInsertSchema = z.object({
  industry_id: z.number(),
  user_id: z.string(),
});

export const uUserIndustriesUpdateSchema = z.object({
  industry_id: z.number().optional(),
  user_id: z.string().optional(),
});

export const uUserIndustryInterestsRowSchema = z.object({
  industry: z.number(),
  user: z.string(),
});

export const uUserIndustryInterestsInsertSchema = z.object({
  industry: z.number(),
  user: z.string(),
});

export const uUserIndustryInterestsUpdateSchema = z.object({
  industry: z.number().optional(),
  user: z.string().optional(),
});

export const uUserInterestsRowSchema = z.object({
  interest: z.number(),
  user: z.string(),
});

export const uUserInterestsInsertSchema = z.object({
  interest: z.number(),
  user: z.string(),
});

export const uUserInterestsUpdateSchema = z.object({
  interest: z.number().optional(),
  user: z.string().optional(),
});

export const uUserReviewsRowSchema = z.object({
  created_at: z.string(),
  detail: z.string().nullable(),
  id: z.number(),
  reviewer_id: z.string(),
  star: z.number(),
  title: z.string(),
  user_id: z.string(),
});

export const uUserReviewsInsertSchema = z.object({
  created_at: z.string().optional(),
  detail: z.string().optional().nullable(),
  id: z.number().optional(),
  reviewer_id: z.string(),
  star: z.number(),
  title: z.string(),
  user_id: z.string(),
});

export const uUserReviewsUpdateSchema = z.object({
  created_at: z.string().optional(),
  detail: z.string().optional().nullable(),
  id: z.number().optional(),
  reviewer_id: z.string().optional(),
  star: z.number().optional(),
  title: z.string().optional(),
  user_id: z.string().optional(),
});

export const uUserSkillsRowSchema = z.object({
  skill: z.number(),
  user: z.string(),
});

export const uUserSkillsInsertSchema = z.object({
  skill: z.number(),
  user: z.string(),
});

export const uUserSkillsUpdateSchema = z.object({
  skill: z.number().optional(),
  user: z.string().optional(),
});

export const userReviewRowSchema = z.object({
  comment: z.string().nullable(),
  cooperation: z.number().nullable(),
  credibility: z.number().nullable(),
  growth: z.number().nullable(),
  response_speed: z.number().nullable(),
  reviewee_id: z.string(),
  reviewer_id: z.string(),
  sincerity: z.number().nullable(),
});

export const userReviewInsertSchema = z.object({
  comment: z.string().optional().nullable(),
  cooperation: z.number().optional().nullable(),
  credibility: z.number().optional().nullable(),
  growth: z.number().optional().nullable(),
  response_speed: z.number().optional().nullable(),
  reviewee_id: z.string(),
  reviewer_id: z.string(),
  sincerity: z.number().optional().nullable(),
});

export const userReviewUpdateSchema = z.object({
  comment: z.string().optional().nullable(),
  cooperation: z.number().optional().nullable(),
  credibility: z.number().optional().nullable(),
  growth: z.number().optional().nullable(),
  response_speed: z.number().optional().nullable(),
  reviewee_id: z.string().optional(),
  reviewer_id: z.string().optional(),
  sincerity: z.number().optional().nullable(),
});

export const usersRowSchema = z.object({
  avatar_url: z.string().nullable(),
  birthday: z.string().nullable(),
  company_established_year: z.number().nullable(),
  company_homepage: z.string().nullable(),
  company_name: z.string().nullable(),
  created_at: z.string().nullable(),
  email: z.string().nullable(),
  expo_push_notification_token: z.string().nullable(),
  firstname: z.string().nullable(),
  firstname_kana: z.string().nullable(),
  hide_age: z.boolean().nullable(),
  hide_in_recommend: z.boolean().nullable(),
  id: z.string(),
  ignore_app_settings: z.boolean().nullable(),
  introduction: z.string().nullable(),
  invited_by: z.string().nullable(),
  is_debug_premium: z.boolean().nullable(),
  job_join_date: z.string().nullable(),
  job_left_date: z.string().nullable(),
  job_position: z.string().nullable(),
  last_active_datetime: z.string().nullable(),
  last_recommended_date: z.string().nullable(),
  lastname: z.string().nullable(),
  lastname_kana: z.string().nullable(),
  line_data: jsonSchema.nullable(),
  location: z.string().nullable(),
  profile_bg_url: z.string().nullable(),
  revenuecat_app_user_id: z.string().nullable(),
  salary_range: z.string().nullable(),
  sns_link1: z.string().nullable(),
  sns_link2: z.string().nullable(),
  sns_link3: z.string().nullable(),
  staff_status: z.string().nullable(),
  stripe_customer_id: z.string().nullable(),
  stripe_subscription_id: z.string().nullable(),
});

export const usersInsertSchema = z.object({
  avatar_url: z.string().optional().nullable(),
  birthday: z.string().optional().nullable(),
  company_established_year: z.number().optional().nullable(),
  company_homepage: z.string().optional().nullable(),
  company_name: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  email: z.string().optional().nullable(),
  expo_push_notification_token: z.string().optional().nullable(),
  firstname: z.string().optional().nullable(),
  firstname_kana: z.string().optional().nullable(),
  hide_age: z.boolean().optional().nullable(),
  hide_in_recommend: z.boolean().optional().nullable(),
  id: z.string(),
  ignore_app_settings: z.boolean().optional().nullable(),
  introduction: z.string().optional().nullable(),
  invited_by: z.string().optional().nullable(),
  is_debug_premium: z.boolean().optional().nullable(),
  job_join_date: z.string().optional().nullable(),
  job_left_date: z.string().optional().nullable(),
  job_position: z.string().optional().nullable(),
  last_active_datetime: z.string().optional().nullable(),
  last_recommended_date: z.string().optional().nullable(),
  lastname: z.string().optional().nullable(),
  lastname_kana: z.string().optional().nullable(),
  line_data: jsonSchema.optional().nullable(),
  location: z.string().optional().nullable(),
  profile_bg_url: z.string().optional().nullable(),
  revenuecat_app_user_id: z.string().optional().nullable(),
  salary_range: z.string().optional().nullable(),
  sns_link1: z.string().optional().nullable(),
  sns_link2: z.string().optional().nullable(),
  sns_link3: z.string().optional().nullable(),
  staff_status: z.string().optional().nullable(),
  stripe_customer_id: z.string().optional().nullable(),
  stripe_subscription_id: z.string().optional().nullable(),
});

export const usersUpdateSchema = z.object({
  avatar_url: z.string().optional().nullable(),
  birthday: z.string().optional().nullable(),
  company_established_year: z.number().optional().nullable(),
  company_homepage: z.string().optional().nullable(),
  company_name: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  email: z.string().optional().nullable(),
  expo_push_notification_token: z.string().optional().nullable(),
  firstname: z.string().optional().nullable(),
  firstname_kana: z.string().optional().nullable(),
  hide_age: z.boolean().optional().nullable(),
  hide_in_recommend: z.boolean().optional().nullable(),
  id: z.string().optional(),
  ignore_app_settings: z.boolean().optional().nullable(),
  introduction: z.string().optional().nullable(),
  invited_by: z.string().optional().nullable(),
  is_debug_premium: z.boolean().optional().nullable(),
  job_join_date: z.string().optional().nullable(),
  job_left_date: z.string().optional().nullable(),
  job_position: z.string().optional().nullable(),
  last_active_datetime: z.string().optional().nullable(),
  last_recommended_date: z.string().optional().nullable(),
  lastname: z.string().optional().nullable(),
  lastname_kana: z.string().optional().nullable(),
  line_data: jsonSchema.optional().nullable(),
  location: z.string().optional().nullable(),
  profile_bg_url: z.string().optional().nullable(),
  revenuecat_app_user_id: z.string().optional().nullable(),
  salary_range: z.string().optional().nullable(),
  sns_link1: z.string().optional().nullable(),
  sns_link2: z.string().optional().nullable(),
  sns_link3: z.string().optional().nullable(),
  staff_status: z.string().optional().nullable(),
  stripe_customer_id: z.string().optional().nullable(),
  stripe_subscription_id: z.string().optional().nullable(),
});
