// This file is auto-generated by supabase/generate-zod-schema.ts. Do not edit manually.

import { z } from 'zod';

export const jsonSchema = z.any();

export const profilesRowSchema = z.object({
  avatar_url: z.string().nullable(),
  created_at: z.string(),
  email: z.string().nullable(),
  full_name: z.string().nullable(),
  id: z.string(),
  updated_at: z.string(),
  user_id: z.string(),
});

export const profilesInsertSchema = z.object({
  avatar_url: z.string().optional().nullable(),
  created_at: z.string().optional(),
  email: z.string().optional().nullable(),
  full_name: z.string().optional().nullable(),
  id: z.string().optional(),
  updated_at: z.string().optional(),
  user_id: z.string(),
});

export const profilesUpdateSchema = z.object({
  avatar_url: z.string().optional().nullable(),
  created_at: z.string().optional(),
  email: z.string().optional().nullable(),
  full_name: z.string().optional().nullable(),
  id: z.string().optional(),
  updated_at: z.string().optional(),
  user_id: z.string().optional(),
});

export const userActivityLogsRowSchema = z.object({
  created_at: z.string(),
  duration: z.number(),
  id: z.string(),
  profile_id: z.string(),
  timestamp: z.number(),
  title: z.string().nullable(),
  updated_at: z.string(),
  url: z.string(),
});

export const userActivityLogsInsertSchema = z.object({
  created_at: z.string().optional(),
  duration: z.number(),
  id: z.string().optional(),
  profile_id: z.string(),
  timestamp: z.number(),
  title: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  url: z.string(),
});

export const userActivityLogsUpdateSchema = z.object({
  created_at: z.string().optional(),
  duration: z.number().optional(),
  id: z.string().optional(),
  profile_id: z.string().optional(),
  timestamp: z.number().optional(),
  title: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  url: z.string().optional(),
});
